#!/usr/bin/env bash
set -euo pipefail

# SparkInfer was formerly named B12X. Keep the legacy Docker build arguments
# internal so existing cache layers and downstream recipes remain compatible.
export B12X_REPO="${SPARKINFER_REPO:-${B12X_REPO:-https://github.com/local-inference-lab/sparkinfer.git}}"
export B12X_REF="${SPARKINFER_REF:-${B12X_REF:-master}}"
export B12X_COMMIT="${SPARKINFER_COMMIT:-${B12X_COMMIT:-}}"
export B12X_PATCH_FILE="${SPARKINFER_PATCH_FILE:-${B12X_PATCH_FILE:-}}"
export B12X_PATCH_SHA256="${SPARKINFER_PATCH_SHA256:-${B12X_PATCH_SHA256:-}}"
export REQUIRE_CLEAN_B12X_COMPOSITION="${REQUIRE_CLEAN_SPARKINFER_COMPOSITION:-${REQUIRE_CLEAN_B12X_COMPOSITION:-0}}"
export B12X_INTEGRATION_LOCK_FILE="${SPARKINFER_INTEGRATION_LOCK_FILE:-${B12X_INTEGRATION_LOCK_FILE:-}}"
export B12X_INTEGRATION_BASE_COMMIT="${SPARKINFER_INTEGRATION_BASE_COMMIT:-${B12X_INTEGRATION_BASE_COMMIT:-}}"
export B12X_INTEGRATION_TREE="${SPARKINFER_INTEGRATION_TREE:-${B12X_INTEGRATION_TREE:-}}"
export B12X_INTEGRATION_PRS="${SPARKINFER_INTEGRATION_PRS:-${B12X_INTEGRATION_PRS:-}}"
export B12X_INTEGRATION_LOCK_SHA256="${SPARKINFER_INTEGRATION_LOCK_SHA256:-${B12X_INTEGRATION_LOCK_SHA256:-}}"

exec "$(dirname "$0")/build-vllm-b12x-cu132.sh" "$@"
